/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PrimerDesign;
import javax.swing.SwingConstants;

/**
 *
 * @author 0907822r
 */
public class FinalTemperaturePanel extends javax.swing.JPanel {

    /**
     * Creates new form FinalTemperaturePanel
     */
    public FinalTemperaturePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator(SwingConstants.VERTICAL);
        reversePrimerNameLabel = new javax.swing.JLabel();
        forwardPrimerNameLabel1 = new javax.swing.JLabel();
        reversePrimerLabel = new javax.swing.JLabel();
        forwardPrimerLabel = new javax.swing.JLabel();
        meltTempNameLabelL = new javax.swing.JLabel();
        meltTempNameLabelR = new javax.swing.JLabel();
        meltTempLabelForward = new javax.swing.JLabel();
        meltTempLabelReverse = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        titleLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Melting Temperatures");

        reversePrimerNameLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        reversePrimerNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reversePrimerNameLabel.setText("Reverse Primer");

        forwardPrimerNameLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        forwardPrimerNameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forwardPrimerNameLabel1.setText("Forward Primer");

        reversePrimerLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        reversePrimerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reversePrimerLabel.setText(PrimerDesign.start.getInSequence().getRPrimer().toString());

        forwardPrimerLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        forwardPrimerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forwardPrimerLabel.setText(PrimerDesign.start.getInSequence().getFPrimer().toString());

        meltTempNameLabelL.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        meltTempNameLabelL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        meltTempNameLabelL.setText("Melting Temperature");

        meltTempNameLabelR.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        meltTempNameLabelR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        meltTempNameLabelR.setText("Melting Temperature");

        meltTempLabelForward.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        meltTempLabelForward.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        meltTempLabelForward.setText(Integer.toString(PrimerDesign.start.getInSequence().getFPrimer().getMeltingTemp()) + "\u2103");
        meltTempLabelForward.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        meltTempLabelReverse.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        meltTempLabelReverse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        meltTempLabelReverse.setText(Integer.toString(PrimerDesign.start.getInSequence().getRPrimer().getMeltingTemp()) + "\u2103");
        meltTempLabelReverse.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTextPane1.setEditable(false);
        jTextPane1.setText("\n\nCongratulations, your primers meet all requirements!\n\nYou should now go to the NCBI website and perform a \"Primer Blast\" on your primers by going to the following website, (insert link here), or by following instructions on your worksheet.\n\nClick the back button to return to earlier stages if you wish to review anything you have done.\n\nClick the next button to see an animation of the results you have provided.\n\nWhen you are done, close this program by closing the window. ");
        jTextPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTextPane1);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        nextButton.setText("See Animation");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(forwardPrimerNameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(forwardPrimerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(meltTempNameLabelL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(meltTempLabelForward, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reversePrimerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reversePrimerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(meltTempNameLabelR, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(meltTempLabelReverse, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {forwardPrimerLabel, forwardPrimerNameLabel1, meltTempLabelForward, meltTempLabelReverse, meltTempNameLabelL, meltTempNameLabelR, reversePrimerLabel, reversePrimerNameLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(forwardPrimerNameLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(forwardPrimerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(meltTempNameLabelL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(meltTempLabelForward, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reversePrimerNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reversePrimerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(meltTempNameLabelR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(meltTempLabelReverse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(nextButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        PrimerDesign.window.getContentPane().remove(PrimerDesign.temperature);
        PrimerDesign.window.setVisible(false);
        
        PrimerDesign.window.getContentPane().add(PrimerDesign.primerSelect);
        PrimerDesign.window.pack();
        PrimerDesign.window.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        String[] x = new String [1];        // What does this do? -Dan
        x[0] = "";
        
        PrimerDesign.window.remove(PrimerDesign.temperature);
        PrimerDesign.window.setVisible(false);
        
        view.PCRAnimation.main(x);
    }//GEN-LAST:event_nextButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel forwardPrimerLabel;
    private javax.swing.JLabel forwardPrimerNameLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel meltTempLabelForward;
    private javax.swing.JLabel meltTempLabelReverse;
    private javax.swing.JLabel meltTempNameLabelL;
    private javax.swing.JLabel meltTempNameLabelR;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel reversePrimerLabel;
    private javax.swing.JLabel reversePrimerNameLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
