/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PrimerDesign;
import java.awt.Color;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import model.TestResult;
import model.TestResult.PassState;

/**
 *
 * @author Robert
 */
public class IndividualEvaluationDialog extends javax.swing.JDialog {

    /**
     * Creates new form ForwardEvaluationDialog
     */
    public IndividualEvaluationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        TestResult test;
        if (PrimerDesign.primerSelect.useF) {
            test = PrimerDesign.primerSelect.fTest;
        }
        else {
            test = PrimerDesign.primerSelect.rTest;
        }
        initComponents();
        
        StyleContext sc = new StyleContext();
        Style defaultStyle = sc.getStyle(StyleContext.DEFAULT_STYLE);
        
        final DefaultStyledDocument doc = new DefaultStyledDocument(sc);
        
        final Style passStyle = sc.addStyle("PassStyle", defaultStyle);
        StyleConstants.setFontFamily(passStyle, "monospaced");
        StyleConstants.setForeground(passStyle, Color.GREEN);
        
        final Style closeFailStyle = sc.addStyle("CloseFailStyle", defaultStyle);
        StyleConstants.setFontFamily(closeFailStyle, "monospaced");
        StyleConstants.setForeground(closeFailStyle, Color.ORANGE);
        
        final Style failStyle = sc.addStyle("FailStyle", defaultStyle);
        StyleConstants.setFontFamily(failStyle, "monospaced");
        StyleConstants.setForeground(failStyle, Color.RED);        
        
        doc.setLogicalStyle(0, defaultStyle);
        try {doc.insertString(0, test.toString(), null);}
        catch(BadLocationException e) {}
        
        infoTextPane.setDocument(doc);
        
        int strIndex = 0, i, length;
        for (i = 0; i < test.size(); i++) {
            length = test.getOut(i).length();
            if (test.getPass(i) == PassState.PASS) {
                doc.setCharacterAttributes(strIndex, length, passStyle, false);
            }
            else if (test.getPass(i) == PassState.CLOSEFAIL) {
                doc.setCharacterAttributes(strIndex, length, closeFailStyle, false);
            }
            else if (test.getPass(i) == PassState.FAIL) {
                doc.setCharacterAttributes(strIndex, length, failStyle, false);
            }
            else {
                doc.setCharacterAttributes(strIndex, length, defaultStyle, false);
            }
            strIndex += length + 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(43, 29));
        okButton.setMinimumSize(new java.awt.Dimension(43, 29));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        infoTextPane.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(infoTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(325, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IndividualEvaluationDialog dialog = new IndividualEvaluationDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane infoTextPane;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
