/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PrimerDesign;
import java.awt.Color;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import model.TestResult;
import model.TestResult.PassState;

/**
 *
 * @author 0907822r
 */
public class PrimerEvaluationDialog extends javax.swing.JDialog {

    /**
     * Creates new form PrimerEvaluationDialog
     */
    public PrimerEvaluationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        
        TestResult test = PrimerDesign.primerSelect.test;
        
        StyleContext sc = new StyleContext();
        Style defaultStyle = sc.getStyle(StyleContext.DEFAULT_STYLE);
        
        final DefaultStyledDocument doc = new DefaultStyledDocument(sc);
        
        final Style passStyle = sc.addStyle("PassStyle", defaultStyle);
        StyleConstants.setFontFamily(passStyle, "monospaced");
        StyleConstants.setForeground(passStyle, Color.GREEN);
        
        final Style closeFailStyle = sc.addStyle("CloseFailStyle", defaultStyle);
        StyleConstants.setFontFamily(closeFailStyle, "monospaced");
        StyleConstants.setForeground(closeFailStyle, Color.ORANGE);
        
        final Style failStyle = sc.addStyle("FailStyle", defaultStyle);
        StyleConstants.setFontFamily(failStyle, "monospaced");
        StyleConstants.setForeground(failStyle, Color.RED);        
        
        doc.setLogicalStyle(0, defaultStyle);
        try {doc.insertString(0, test.toString(), null);}
        catch(BadLocationException e) {System.out.println("Herp.");}
        
        infoTextPane.setDocument(doc);
        
        int strIndex = 0, i, length;
        for (i = 0; i < test.size(); i++) {
            length = test.getOut(i).length();
            if (test.getPass(i) == PassState.PASS) {
                doc.setCharacterAttributes(strIndex, length, passStyle, false);
                System.out.println(strIndex + " " + length + 
                        test.toString().substring(strIndex, strIndex+length));
            }
            else if (test.getPass(i) == PassState.CLOSEFAIL) {
                doc.setCharacterAttributes(strIndex, length, closeFailStyle, false);
            }
            else if (test.getPass(i) == PassState.FAIL) {
                doc.setCharacterAttributes(strIndex, length, failStyle, false);
            }
            else {
                doc.setCharacterAttributes(strIndex, length, defaultStyle, false);
            }
            strIndex += length + 1;
        }
        
        if (PrimerDesign.primerSelect.getAttempts() > 3)
                overrideButton.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        overrideButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToggleButton1.setText("OK");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        overrideButton.setText("Accept & Continue");
        overrideButton.setEnabled(false);
        overrideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overrideButtonActionPerformed(evt);
            }
        });

        infoTextPane.setEditable(false);
        infoTextPane.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(infoTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 586, Short.MAX_VALUE)
                        .addComponent(overrideButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(overrideButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void overrideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overrideButtonActionPerformed
        PrimerDesign.primerSelect.setPass(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_overrideButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimerEvaluationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimerEvaluationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimerEvaluationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimerEvaluationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PrimerEvaluationDialog dialog = new PrimerEvaluationDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane infoTextPane;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton overrideButton;
    // End of variables declaration//GEN-END:variables
}
